jobs:
  auth:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate with Workload Identity and Impersonate Service Account
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          impersonate_service_account: ${{ secrets.TARGET_SERVICE_ACCOUNT_EMAIL }}


      - name: Test GCP Command
        run: |
          gcloud auth list
