name: Run Cloud CLI Commands

on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read

jobs:
  run-cli:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # - name: Configure Google Cloud Auth
      #   uses: google-github-actions/auth@v1
      #   with:
      #     workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      #     service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Authenticate with Workload Identity and Impersonate Service Account
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
          access_token_subject: ${{ secrets.TARGET_SERVICE_ACCOUNT_EMAIL }}
          # impersonate_service_account: ${{ secrets.TARGET_SERVICE_ACCOUNT_EMAIL }}
          # create_credentials_file: true
          # export_environment_variables: true

      - name: Impersonate Service Account and Test GCP Command
        run: |
          gcloud config set auth/impersonate_service_account ${{ secrets.TARGET_SERVICE_ACCOUNT_EMAIL }}
          gcloud projects list
          # gcloud auth activate-service-account --key-file=${{ secrets.GCP_CREDENTIALS_FILE }}
          # gcloud auth print-access-token --impersonate-service-account=${{ secrets.TARGET_SERVICE_ACCOUNT_EMAIL }}

      - name: Run GCP Commands
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          gcloud config set project $PROJECT_ID
          gcloud auth list
          gcloud iam service-accounts list --project=$PROJECT_ID

          # Add more commands as needed
