name: Run Cloud CLI Commands

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  run-cli:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure Google Cloud Auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/989320585748/locations/global/workloadIdentityPools/github-pool/providers/github-provider2
          service_account: gha-runner@excellent-grin-302222.iam.gserviceaccount.com
          access_token_scopes: https://www.googleapis.com/auth/cloud-platform

      - name: Run GCP Commands
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          gcloud config set project $PROJECT_ID
          gcloud auth list
          gcloud iam service-accounts list --project=$PROJECT_ID

          # Add more GCP commands here as needed
